apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: nqiic32kg-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/nqiic32kg-java-springboot-gitops